#!/usr/bin/env bash
# Writes /usr/share/nginx/html/env.js from real env vars so the SPA bundle
# can read the API URL at runtime instead of having it baked in at build
# time. Dropped into /docker-entrypoint.d/ so nginx's own entrypoint script
# runs it before starting the server.

set -euo pipefail

API_BASE_URL="${API_BASE_URL:-http://localhost:8080}"

cat > /usr/share/nginx/html/env.js <<EOF
// Generated by docker-entrypoint.sh at container start.
window.__RUNTIME_CONFIG__ = {
  API_BASE_URL: "${API_BASE_URL}"
};
EOF

echo "[runtime-config] Wrote /env.js with API_BASE_URL=${API_BASE_URL}"
